language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script:
  - bash -ex .travis-opam.sh
  - bash -ex build.sh
env:
  - OCAML_VERSION=4.02
os:
  - linux
